#!/bin/sh
#
# Will be named:
# /usr/share/initramfs-tools/scripts/local-top/ykfde
#

set -e

PREREQ=""

prereqs()
{
    echo "$PREREQ"
}

case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

if [ -e /etc/yubikey-challenge ]; then
    CRYPTTAB="/cryptroot/crypttab"
    [ -f "/conf/conf.d/cryptroot" ] && CRYPTTAB="/conf/conf.d/cryptroot"
    sed -i 's|$|,keyscript=/sbin/ykfde-keyscript|' ${CRYPTTAB}
fi

exit 0